### ISSUE TITLE
Errors when running slides:watch & slides:build on Ubuntu 20.04

### ISSUE THREAD

**Issue by CodeSpent** [cmgriffing/servante#16]
When running `npm run slides:watch` I'm met with the following error.

```
❱ npm run slides:watch

> cocode-orientation@0.0.0 slides:watch /home/phanford/Development/cocode-orientation
> nodemon --exec "npm run slides:build" slides/*.md

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: md,json
[nodemon] starting `npm run slides:build slides/01-intro.md slides/02-about-me.md slides/999-outro.md`

> cocode-orientation@0.0.0 slides:build /home/phanford/Development/cocode-orientation
> run-s slides:assets  slides:build:pandoc "slides/01-intro.md" "slides/02-about-me.md" "slides/999-outro.md"

ERROR: Task not found: "slides/01-intro.md", slides/02-about-me.md", slides/999-outro.md"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cocode-orientation@0.0.0 slides:build: `run-s slides:assets  slides:build:pandoc "slides/01-intro.md" "slides/02-about-me.md" "slides/999-outro.md"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cocode-orientation@0.0.0 slides:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/phanford/.npm/_logs/2021-01-10T23_09_05_099Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...
```

When running `npm run slides:build` I'm met with another error that may or may not be related to the same issue.

```
❱ npm run slides:build

> cocode-orientation@0.0.0 slides:build /home/phanford/Development/cocode-orientation
> run-s slides:assets  slides:build:pandoc


> cocode-orientation@0.0.0 slides:assets /home/phanford/Development/cocode-orientation
> run-s slides:assets:mkdirp  slides:assets:cp


> cocode-orientation@0.0.0 slides:assets:mkdirp /home/phanford/Development/cocode-orientation
> shx mkdir -p html/assets


> cocode-orientation@0.0.0 slides:assets:cp /home/phanford/Development/cocode-orientation
> shx cp -PR slides/assets/ html/assets/

/home/phanford/Development/cocode-orientation/node_modules/shelljs/src/common.js:399
        throw e;
        ^

Error [ShellJSInternalError]: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at copyFileSync (/home/phanford/Development/cocode-orientation/node_modules/shelljs/src/cp.js:70:22)
    at /home/phanford/Development/cocode-orientation/node_modules/shelljs/src/cp.js:298:7
    at Array.forEach (<anonymous>)
    at _cp (/home/phanford/Development/cocode-orientation/node_modules/shelljs/src/cp.js:243:11)
    at /home/phanford/Development/cocode-orientation/node_modules/shelljs/src/common.js:384:25
    at shx (/home/phanford/Development/cocode-orientation/node_modules/shx/lib/shx.js:139:37)
    at run (/home/phanford/Development/cocode-orientation/node_modules/shx/lib/cli.js:20:31)
    at Object.<anonymous> (/home/phanford/Development/cocode-orientation/node_modules/shx/lib/cli.js:39:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cocode-orientation@0.0.0 slides:assets:cp: `shx cp -PR slides/assets/ html/assets/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cocode-orientation@0.0.0 slides:assets:cp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/phanford/.npm/_logs/2021-01-10T23_11_03_994Z-debug.log
ERROR: "slides:assets:cp" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cocode-orientation@0.0.0 slides:assets: `run-s slides:assets:mkdirp  slides:assets:cp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cocode-orientation@0.0.0 slides:assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/phanford/.npm/_logs/2021-01-10T23_11_04_041Z-debug.log
ERROR: "slides:assets" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cocode-orientation@0.0.0 slides:build: `run-s slides:assets  slides:build:pandoc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cocode-orientation@0.0.0 slides:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/phanford/.npm/_logs/2021-01-10T23_11_04_081Z-debug.log
```

The issue with `slides:build` seems like it may be trying to perform a file operation on a directory.

**Platform Specifics:**
- Ubuntu 20.04
- Node v14.15.4
- Npm v6.14.10
- Pandoc v2.11.3.2

**Comment by CodeSpent** [comment]
Hadn't noticed this at first, but it seems like there's a file called `assets` created in the `html/assets` directory during the build.
![image](https://user-images.githubusercontent.com/7674344/104138394-ca936800-5371-11eb-9618-54ae259c7386.png)

**Comment by CodeSpent** [comment]
Appears the fix is just changing `shx cp -PR slides/assets/ html/assets/` to `shx cp -PR slides/assets/* html/assets/` to copy all files in the `slides/assets` directory recursively rather than (on Linux) copying the directory or a file by same name of the directory.

Will be submitting a pull request as soon as I confirm this is Windows compatible!
